#!/bin/bash
clear

echo -e "\nIn this game you decide the fate an adventurer that has been out dungeon crawling. Your adventurer is a seasoned dungeon looter and has plenty of experience fighting mythical creatures and escaping dangerous traps. Though smaller than the average Human, your adventurer can still take on some big problems. It is up to you to get the adventerer through the rest of this dungeon safely in order to win the game.\n"

echo -e "\nThe story starts mid dungeon as your adventurer is creeping through a corridor, trying to keep a look out for any traps. Suddenly, they step on a preassure plate, casuing it to sink into the floor. Flames burst out of the corridor behind them, filling it quickly. They sprint forward, trying to get to the door at then end of the corridor, in hopes to make it there before the flames can burn them to a crisp. The adventurer is running as fast as they can and can start to feel the heat of the fire on their back. They lunge in the door and close it hastily behind them, as a few flames manage to make it through.\n"

echo -e "\nThis is where you take control of the adventurer. Here are a few tips for the game, that way you get the correct results and have a fun time playing.\n"
echo -e "\n1. Type your answers exactly as promted. This game uses if/else statements and if you dont type your answer correctly you'll get the wrong results.\n"
echo -e "\n2. If you pick an answer and it results poorly, don't worry, you'll have an opportunity to restart.\n"
echo -e "\n3. also remember, no capital letters!\n"

sleep 20
#naming the adventurer
function name() {
echo -e "\nNow, what is the name of your adventurer? This is a fantasy world, so you can be creative!\n"
read name
echo -e "\nYou entered $name. Are you sure you want this to be their name?(y/n)\n"
read answer
if [ $answer = 'y' -o $answer = 'yes' ]
then
echo -e "\nGreat!, lets continue the adventure!\n"
sleep 3
begin
else
name
fi
}


#start of the game
function begin() {
clear
echo
echo -e "\n$name catches their breath and takes a look around the room. It seems to be a common room of sorts, having a chair and table in the center of the room. There are 3 other doors in the room, one on the left, one on the right, and one directly accross. $name can see through the doors becasue of the jail like windows they have on them. The door on the left is full of random boxes. The door on the right has a bunch of orcs in their bunks sleeping, its probably best not to wake them. $name gr Finally the door ahead has two sets of stairs, one leading up and one down. Which door would you like $name to go through? (left/straight)\n"
read answer
if [ $answer = '1' ]
then
echo -e "\n$name goes through the left door.\n"
left
else
echo -e "\n$name goes through the door straight ahead.\n"
straight
fi
}


#door1
function left() {
echo -e "\nThere is stuff piled high to the ceiling. On the far side of the room you see a door, but it is blocked by something that looks heavy.$name searches for something to move the heavy object. They find a wooden handle handle that could wedge the object out of the way, but will topple the boxes it supports. Would you like $name to go back through the other door? Or would you like them to use the handle to wedge the oject out of the way? (wedge/goback)\n"
read answer
if [ $answer = 'goback' ]
then
straight
else
echo -e "\n$name grabs the wooden handle handle that seems to be supporting the pile, but causes an avalanche in the room. $name is crushed by all the debris, killing them instantly.\n"
youlose
fi
}


#door2
function straight() {
echo -e "\nThe stairs leading up have a soft glowing light radiating from it, and a soft chatter can be heard between a few individuals. The stairs leading down are pitch black and you can't see a bottom, but there is a torch hanging on the wall that $name could take with them. Would you like them to go up or down? (up/down)\n"
read answer
if [ $answer = "up" ]
then
echo -e "\n$name takes the stairs leading up.\n"
upstairs
else
echo -e "\n$name grabs the torch and takes the stairs leading down.\n"
downstairs
fi                 
}


#upstairs
function upstairs() {
echo -e "\nAfter going up the stairs, $name comes accross two green creatures talking to each other. They look tattered and battle hardened, with scars all over. They are Orcs! One of them notices you and shouts, 'Oi! 'oo is this lot?' They both stand and face you, grasping raggedy swords. 'I 'ont know, but 'e ain't suppose' tuh be 'ere!' They both start to charge $name, ready to kill! Quick, should $name counter attack or run away? (counter/run)\n"
read answer
if [ $answer = 'counter' ]
then
echo -e "\n$name counter attacks the Orcs!\n"
counter
else
echo -e "\n$name tries to run but the orcs already had a start on them. They plung their swords into $name's back and they slowly bleed out. 'This one'll make a nice meal!' They chop $name up and use them for a stew.\n"
youlose
fi
}


#counter
function counter() {
echo -e "\nThey knock one to the ground but the other grabs them. The orc on the ground gets up and says to $name 'im 'unna gut you like a fish!' Should $name try to kick the ork, or struggle free?(kick/struggle)\n"
read answer
if [ $answer = 'kick' ]
then
echo -e "\n$name kicks the orc in front of them!\n"
kick
else
struggle
fi
}


#kickorc
function kick() {
echo -e "\n$name and the orc holding them tumble to the ground, losing his grasp of $name. As $name gains their bearing, they see one of the orc's swords in front of them. Do you want $name to grab the sword and fight or should they try to run away while they have the best of the orcs. (grab/run)\n"
read answer
if [ $answer = 'grab' ]
then
echo -e "\n$name lunges for the sword!\n"
grabsword
else
echo -e "\n\n"
youlose
fi
}


#grabsword
function grabsword() {
echo "Taking up the sword, you face the orcs. One of them grabs a sword and the other pulls a knife from a sheath behind their back. They charge you but you're ready. $name slash the first orc across the chest and he falls to the floor in pain. The second or swings at you with his knife but you dodge back, causing him to go off balance. $name swipe at his neck, toppling his head to the floor. Suddenly, you hear a long deep horn. The orc on the floor has called for backup. $name finish the job, but you hear many footsteps quickly apporaching. $name, $name can try to un, but dont know how close the approaching orcs are, or you could stay and try to hold them off for as long as possible. What would you like to do? (run/fight) "
read answer
if [ $answer = 'run' ]
then
#player runs and goes downstairs
echo -e "\n$name goes down the stairs they came up. they can hear orcs in the room they once started in. There is nowhere else to go other than to take the stairs leading into the unknown. $name grabs the torch and starts to head down."
downstairs
else
#fighting to last breath
echo -e "\n$name readies their sword and faces the stairs from which they came from."
youlose
fi
}



#struggle
function struggle() {
echo -e "\n$name attempt to struggle free but there is no use, the orc holding you is stronger.\n"
counter
}


#downstairs
function downstairs() {
echo -e "\nAfter traveling for what seemed like miles down the stairs, $name finally reached the bottom of the stairs into what seems to be a long dark hallway. As they veture forth, $name comes to a fork in the hall. Would you like $name to travel left or right?(left/right)"
read answer
if [ answer = 'left' ]
then
echo -e "\n$name travels left."
lefthall
else
echo -e "\n$name travesl right."
righthall
fi
}


#lefthall
function lefthall() {
echo -e ""
read answer
if [ $answer = 'jump']
then
echo ""
jump
else
echo ""
youlose
fi
}

#righthall
function righthall() {
echo
read answer
if [$answer = 'crawl']
then
echo ""
crawl
else
echo ""
youlose
fi
}

#$name lose screen
function youlose() {
sleep 8
echo -e "\n$name Lose! Would you like to play again? (y/n)\n"
read answer
if [ $answer = 'y' ]
then
begin
else
clear
echo -e "\nThank you for playing!\n"
fi
}


name
