#!/bin/bash
clear
function intro() {
echo -e "\nIn this game you decide the fate an adventurer that has been out dungeon crawling. Your adventurer is a seasoned dungeon looter and has plenty of experience fighting mythical creatures and escaping dangerous traps. Though smaller than the average Human, your adventurer can still take on some big problems. It is up to you to get the adventerer through the rest of this dungeon safely in order to win the game.\n"

echo -e "\nThe story starts mid dungeon as your adventurer is creeping through a corridor, trying to keep a look out for any traps. Suddenly, they step on a preassure plate, causing it to sink into the floor. Flames burst out of the corridor behind them, filling it quickly. They sprint forward, trying to get to the door at then end of the corridor, in hopes to make it there before the flames can burn them to a crisp. The adventurer is running as fast as they can and can start to feel the heat of the fire on their back. They lunge in the door and close it hastily behind them, as a few flames manage to make it through.\n"

echo -e "\nThis is where you take control of the adventurer. Here are a few tips for the game, that way you get the correct results and have a fun time playing.\n"
echo -e "\n1. Type your answers exactly as promted. This game uses if/else statements and if you dont type your answer correctly you'll get the wrong results.\n"
echo -e "\n2. If you pick an answer and it results poorly, don't worry, you'll have an opportunity to restart.\n"
echo -e "\n3. also remember, no capital letters!\n"
sleep 20
name
}
#naming the adventurer
function name() {
echo -e "\nNow, what is the name of your adventurer? This is a fantasy world, so you can be creative!\n"
read name
echo -e "\nYou entered $name. Are you sure you want this to be their name?(y/n)\n"
read answer
if [ $answer = 'y' -o $answer = 'yes' ]
then
echo -e "\nGreat!, lets continue the adventure!\n"
sleep 3
begin
else
name
fi
}


#start of the game
function begin() {
clear
echo
echo -e "\n$name catches their breath and takes a look around the room. It seems to be a common room of sorts, having a chair and table in the center of the room. There are 3 other doors in the room, one on the left, one on the right, and one directly across. $name can see through the doors because of the jail like windows they have on them. The door on the left is full of random boxes. The door on the right has a bunch of orcs in their bunks sleeping, its probably best not to wake them. Lastly, the door ahead has two sets of stairs, one leading up and one down. Which door would you like $name to go through? (left/straight)\n"
read answer
if [ $answer = 'left' ]
then
echo -e "\n$name goes through the left door.\n"
left
else
echo -e "\n$name goes through the door straight ahead.\n"
straight
fi
}


#door1
function left() {
echo -e "\nThere is stuff piled high to the ceiling. On the far side of the room you see a door, but it is blocked by a cabinet that looks heavy. $name searches for something to move it and finds a wooden handle that looks like it could wedge the object out of the way, but its also acting as a substitute table leg for a table that has stuff piled on it. Would you like $name to go back through to the other door? Or would you like them to use the handle to wedge the cabinet out of the way? (wedge/goback)\n"
read answer
if [ $answer = 'goback' ]
then
echo -e "\n$name went back through the common room to the room with stairs."
straight
else
echo -e "\n$name grabs the wooden handle from under the table, the sudden shift in weight causes the pile to topple onto $name, killing them instantly.\n"
youlose
fi
}


#door2
function straight() {
echo -e "\nThe stairs leading up have a soft glowing light radiating from it, and a soft chatter can be heard between a few individuals. The stairs leading down are pitch black and there is no bottom in sight, but there is a torch hanging on the wall that $name could take with them. Would you like them to go up or down? (up/down)\n"
read answer
if [ $answer = "up" ]
then
echo -e "\n$name takes the stairs leading up.\n"
upstairs
else
echo -e "\n$name grabs the torch and takes the stairs leading down.\n"
downstairs
fi                 
}


#upstairs
function upstairs() {
echo -e "\nAfter going up the stairs, $name comes accross two green creatures talking to each other. They look tattered and battle hardened, with scars all over. They are Orcs! One of them notices you and shouts, 'Oi! 'oo is this lot?' They both stand and face you, grasping raggedy swords. 'I 'ont know, but 'e ain't suppose' tuh be 'ere!' They both start to charge $name, ready to kill! Quick, should $name counter attack or run away? (counter/run)\n"
read answer
if [ $answer = 'counter' ]
then
echo -e "\n$name counter attacks the Orcs!\n"
counter
else
echo -e "\n$name tries to run but the orcs already had a start on them. They plung their swords into $name's back and they slowly bleed out. 'This one'll make a nice meal!' They chop $name up and use them for a stew.\n"
youlose
fi
}


#counter
function counter() {
echo -e "\nThey knock one to the ground but the other grabs them. The orc on the ground gets up and says to $name 'im 'unna gut you like a fish!' Should $name try to kick the ork, or struggle free?(kick/struggle)\n"
read answer
if [ $answer = 'kick' ]
then
echo -e "\n$name kicks the orc in front of them!\n"
kick
else
struggle
fi
}


#kickorc
function kick() {
echo -e "\n$name and the orc holding them tumble to the ground, losing his grasp of $name. As $name gains their bearing, they see one of the orc's swords in front of them. Do you want $name to grab the sword and fight or should they try to run away while they have the best of the orcs. (grab/run)\n"
read answer
if [ $answer = 'grab' ]
then
echo -e "\n$name lunges for the sword!\n"
grabsword
else
echo -e "\n$name starts for the stairs bu the orc on the ground grabs their leg, stopping them in their tracks. the orc gracs a knife from a smoll sheath on his belt and cuts into $name's gut. $name clenches their stomach falling to the ground. The orcs finish the fight by cutting of $name's head.\n"
youlose
fi
}


#grabsword
function grabsword() {
echo "Taking up the sword, $name faces the orcs. One of them grabs a sword while the other pulls a knife from a sheath behind their back. The orcs charge but $name is ready. $name slashes the first orc across the chest and he falls to the floor in pain. The second orc swings at $name with his knife but they dodge back, causing te orc to go off balance. $name swipes at his neck, toppling his head to the floor. Suddenly, there was a long deep horn that sounded. The orc on the floor has called for backup. $name finished the job, but there is a sound of many footsteps quickly apporaching. $name can try to run, but doesn't know how close the approaching orcs are, or they could stay and try to hold them off for as long as possible. What would you like $name to do? (run/fight) "
read answer
if [ $answer = 'run' ]
then
#player runs and goes downstairs
echo -e "\n$name goes down the stairs they came up. They can hear orcs in the room they once started in. There is nowhere else to go other than to take the stairs leading into the unknown. $name grabs the torch and starts to head down."
downstairs
else
#fighting to last breath
echo -e "\n$name readies their sword and faces the stairs from which they came from. The first few orcs make it up the stairs and $name makes quick work of them, but $name is getting overwhelmed quickly. $name slashes trough a few more orcs when an arrow travels across the room, piercing $name in the chest. $name falls to their knees slowly losing all control of their limbs. The ors surround $name as if waiting for someting. A bigger orc than all the others enters the room falls silent. He raises a sword and speaks, 'ooks like meat back on tuh menu!' The boss orc brings down his sword ending $name's life.\n"
youlose
fi
}



#struggle
function struggle() {
echo -e "\n$name attempts to struggle free but there is no use, the orc holding them is stronger.\n"
counter
}


#downstairs
function downstairs() {
echo -e "\nAfter traveling down the dark staircase, $name finally reached the bottom into what seems to be a long dark hallway. As they veture forth, $name comes to a fork in the hall. Would you like $name to travel left or right?(left/right)"
read answer
if [ $answer = 'left' ]
then
echo -e "\n$name travels left."
forkleft
else
echo -e "\n$name travels right."
righthall
fi
}

#lefthall
function forkleft() {
echo -e "\nJust ahead there is a giant hole in the ground from what appears to be a trap that was already set off. $name is confident that they can make it across, but if they dont, a pitfall full of spikes awaits the. Do you what $name to try to  make it accross, or turn back and try the other hall? (jump/goback)\n"
read answer
if [ $answer = 'jump' ]
then
echo -e "\n$name takes a few steps back and gets a running start for their leap. They soar across the gap in the floor and make it to the other side! Safely across, $name ventures forth until they reach what seems to be a door to the last room of the dungeon. $name opens the door to find a room full of gold!\n"
youwin
else
echo -e "\nEven though $name is confident they can make it accross, they turn around to try the other hall.\n"
righthall
fi
}


#righthall
function righthall() {
echo -e "\nJust ahead, there is a rolling log trap. $name sees the tripwire that will set off and is confident that they can disarm the trap to make it through. What would you like to do? (back/disarm)\n"
read answer
if [ $answer = 'back' ]
then
echo -e "\nEven though $name thinks they can disarm the trap, they turn around to try the other hall.\n"
forkleft
else
echo "$name goes to disarm the trap, but in doing so they accidentally set it off. The rolling spike log swings towards $name and kills them in one swoop."
youlose
fi
}

#$name lose screen
function youlose() {
sleep 8
echo -e "\nYou Lose! dont worry though, theres only a finie number of outcomes, so youll get to the end eventually. Would you like to play again? (y/n)\n"
read answer
if [ $answer = 'y' ]
then
begin
else
clear
echo -e "\nThank you for playing!\n"
echo -e "\nCreated by Joseph Perales\n"
fi
}

#the player wins the game
function youwin() {
echo -e "\nCongradulations! You safely led $name through the rest of the dungeon, getting them to the treasure!\n"
echo -e "\nWould you like to play again? (y/n)\n"
read answer
if [ $answer = 'y' ]
then
intro
else
echo -e "\nThank you for playing!\n"
echo -e "\nCreated by Joseph Perales\n"
fi
}

intro
